# Generated by Django 5.2.6 on 2025-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='description',
        ),
        migrations.RemoveField(
            model_name='license',
            name='document',
        ),
        migrations.RemoveField(
            model_name='license',
            name='title',
        ),
        migrations.AddField(
            model_name='license',
            name='aadhar_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='address',
            field=models.TextField(default='Default Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/photos/'),
        ),
    ]
